### ISSUE TITLE
Question about persisting data into the DB with Rest API

### ISSUE THREAD

**Issue by vladikata2535** [luchob/softuni-sept-2021-misc#61]
Здрасти Лъчо, 

Исках да те попитам на лекцията, но не ми стигна времето да я гледам на живо, та задължително ли е през RestAPI за проектчето ни да създаваме нов обект и да го слагаме в базата по начина, който ти направи с коментарите или е нужно само да си дръпнем чрез JS fetch api данните и да ги визуализираме, защото мислех да си визуализирам продуктите в склада чрез fetch API, но пък видях, че ти го ползваш и за да създаваш нов запис в базата и ми стана интересно да те попитам дали трябва и ние да го направим или не е задължително.

Лека вечер,
Поздрави В.

**Comment by luchob** [comment]
Здрасти!

Вчера стана кораво, но писането с plain JS рано или късно закоравява. Нищо, другият път ще гледам да го довърша създаването :-) В условието на задачата пише, цитирам:

_Use Fetch instead of AJAX to asynchronously load and display data somewhere in your application._

Мисля, че тове е съвсем недвусмислено и никъде не пише, че е задължително да се правят нови записи. Допускам, идеята е да си види че знаеш какво е REST контролер в спринг, като JS-a ще остава на заден план.

Поздрави,
Л.
